### ISSUE TITLE
missing input data

### ISSUE THREAD

**Issue by brucellino** [aduut/egi_files#2]
Hi @aduut 

running the python scripts, it seems that there is some input data missing. Can we discuss where and what this is please ?

**Comment by duutabib** [comment]
Sure when - which script are you running??

**Comment by brucellino** [comment]
For example : 

```python
python iresnet_script.py 
/home/becker/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-03-30 14:52:47.702695: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "iresnet_script.py", line 44, in <module>
    img = image.load_img(img_path, target_size=(224, 224))
  File "/home/becker/.local/lib/python2.7/site-packages/keras/preprocessing/image.py", line 362, in load_img
    img = pil_image.open(path)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2410, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/0/abib/figures/circlefeature/feature_1.png'
```

The paths are hardcoded to read some filesystem somewhere where the input files (feature<N>) seem to be.

**Comment by duutabib** [comment]
Hello Bruce,

Apologies for my silence. I have recently relocated to Darmstadt from Bremen and I am currently studying at TU Darmstadt. Is been some hectic few weeks.

I wonder if you have time now so I can correct some of the issues... thanks.
(I would fix those errors soon.)

Also I didn't want to submit that job now... is not priority at this time. I want to train a convolutional network. The file 'slmodel_contint.py' is the urgent one now!!

Thanks!!
